# Generated by Django 4.0.4 on 2022-06-12 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_remove_notification_viewed_by_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='owner',
            new_name='sender',
        ),
    ]
