# Generated by Django 4.0.4 on 2022-06-12 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='company',
        ),
    ]
